blank_issues_enabled: true
contact_links:
  - name: Luos Community Support
    url: https://luos.io/community
    about: Please ask and answer questions about Luos here.
  - name: Luos Documentation
    url: https://luos.io/docs
    about: Please read Luos documentation here.
