[build-system]
requires = ["setuptools>=61", "wheel", "cffi>=1.15"]
build-backend = "setuptools.build_meta"

[project]
name = "luos_engine"
version = "0.1.0"
description = "Python binding for the Luos engine"
requires-python = ">=3.10"
dependencies = ["cffi>=1.15", "platformdirs>=3"]

[project.optional-dependencies]
test = ["pytest", "pyluos>=3.1"]

[tool.setuptools]
packages = ["luos_engine"]

[tool.setuptools.package-data]
luos_engine = ["libluos_engine.*", "*.so", "*.dylib", "*.dll"]
